// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsmlaczwtgkxicxxfpco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzbWxhY3p3dGdreGljeHhmcGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODg3NjAsImV4cCI6MjA1OTc2NDc2MH0.i5yZZ0FCrbei3YmJwta5-Zyrgkk5tBMZcrkhgGjsUqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);